

export const INIT_PAY_INFO = 'INIT_PAY_INFO';

export const REQUEST_PAY_INFO_LOADIND = 'REQUEST_THROUGH_INFO_LOADIND';
export const REQUEST_PAY_INFO_ERROR = 'REQUEST_THROUGH_INFO_ERROR';

export const REQUEST_PAY_WECHAT_INFO_SUCCESS = 'REQUEST_THROUGH_INFO_SUCCESS';
export const REQUEST_PAY_ALIPAY_INFO_SUCCESS = 'REQUEST_THROUGH_INFO_SUCCESS';


export const REQUEST_PAY_COUNT_DOWN_LOADING ='REQUEST_PAY_COUNT_DOWN_LOADING';
export const REQUEST_PAY_COUNT_DOWN_ERROR ='REQUEST_PAY_COUNT_DOWN_ERROR'; 
export const REQUEST_BUS_PAY_COUNT_DOWN_SUCCESS ='REQUEST_BUS_PAY_COUNT_DOWN_SUCCESS';
export const REQUEST_TRAIN_PAY_COUNT_DOWN_SUCCESS = 'REQUEST_TRAIN_PAY_COUNT_DOWN_SUCCESS';


