

export const REQUEST_BUS_FILLORDER_LOADIND = 'REQUEST_BUS_FILLORDER_LOADIND';
export const REQUEST_BUS_FILLORDER_ERROR = 'REQUEST_BUS_FILLORDER_ERROR';

export const REQUEST_BUS_FILLORDER_USER_INFO_SUCCESS = "REQUEST_BUS_FILLORDER_USER_INFO_SUCCESS";
export const REQUEST_BUS_FILLORDER_INSURANCE_SUCCESS = "REQUEST_BUS_FILLORDER_INSURANCE_SUCCESS";
export const REQUEST_BUS_FILLORDER_SERVICE_CHARGE_SUCCESS = "REQUEST_BUS_FILLORDER_SERVICE_CHARGE_SUCCESS";



