

export const REQUEST_DATERANGE_LOADING = 'REQUEST_DATERANGE_LOADING' ;
export const REQUEST_DATERANGE_ERROR = 'REQUEST_DATERANGE_ERROR';
export const REQUEST_DATERANGE_SUCCESS = 'REQUEST_DATERANGE_SUCCESS';


export const REQUEST_PACK_LOADING = 'REQUEST_PACK_LOADING' ;
export const REQUEST_PACK_ERROR = 'REQUEST_PACK_ERROR' ;
export const REQUEST_PACK_SUCCESS = 'REQUEST_PACK_SUCCESS' ;



