

export  const REQUEST_ORDER_LOADING = 'REQUEST_ORDER_LOADING';

export  const CHANGE_ORDER_TAB = 'CHANGE_ORDER_TAB';
export  const CHANGE_PAGE ='CHANGE_PAGE';

export  const REQUEST_ORDER_PASSENGERS_ERROR = 'REQUEST_ORDER_PASSENGERS_ERROR';
export  const REQUEST_ORDER_PASSENGERS_SUCCESS = 'REQUEST_ORDER_PASSENGERS_SUCCESS';


