

export  const REQUEST_LOADING = 'REQUEST_LOADING';
export const RESET_ERROR = 'RESET_ERROR';


export  const REQUEST_PASSWNGERS_ERROR = 'REQUEST_PASSWNGERS_ERROR';
export  const REQUEST_PASSWNGERS_SUCCESS = 'REQUEST_PASSWNGERS_SUCCESS';


