


export const RESET_ERROR = 'RESET_ERROR';
export const RESET_PASSENGERS = 'RESET_PASSENGERS';

export  const REQUEST_LOADING = 'REQUEST_LOADING';
export  const REQUEST_ERROR = 'REQUEST_PASSWNGERS_ERROR';


export  const REQUEST_PASSENGERS_INFO_SUCCESS = 'REQUEST_PASSENGERS_INFO_SUCCESS';
export  const REQUEST_ADD_PASSENGERS_SUCCESS = 'REQUEST_ADD_PASSENGERS_SUCCESS'
export  const REQUEST_UPDATE_PASSENGERS_SUCCESS = 'REQUEST_UPDATE_PASSENGERS_SUCCESS'

