

export const REQUEST_BUS_INFO_LOADIND = 'REQUEST_BUS_INFO_LOADIND';
export const REQUEST_BUS_INFO_ERROR = 'REQUEST_BUS_INFO_ERROR';
export const REQUEST_BUS_INFO_SUCCESS = 'REQUEST_BUS_INFO_SUCCESS';


