

export  const REQUEST_ACCOUNT_USER_INFO_LOADING = 'REQUEST_ACCOUNT_USER_INFO_LOADING';
export  const REQUEST_ACCOUNT_USER_INFO_ERROR = 'REQUEST_ACCOUNT_USER_INFO_ERROR';
export  const REQUEST_ACCOUNT_USER_INFO_SUCCESS = 'REQUEST_ACCOUNT_USER_INFO_SUCCESS';

