


export const REQUEST_THROUGH_INFO_LOADIND = 'REQUEST_THROUGH_INFO_LOADIND';
export const REQUEST_THROUGH_INFO_ERROR = 'REQUEST_THROUGH_INFO_ERROR';
export const REQUEST_THROUGH_INFO_SUCCESS = 'REQUEST_THROUGH_INFO_SUCCESS';


