

export const REQUEST_INIT_PARAMS = 'REQUEST_INIT_PARAMS';


export const REQUEST_TRAIN_INFO_LOADIND = 'REQUEST_TRAIN_INFO_LOADIND';
export const REQUEST_TRAIN_INFO_ERROR = 'REQUEST_TRAIN_INFO_ERROR';
export const REQUEST_TRAIN_INFO_SUCCESS = 'REQUEST_TRAIN_INFO_SUCCESS';

export const REQUEST_DATERANGE_LOADING = 'REQUEST_DATERANGE_LOADING' ;
export const REQUEST_DATERANGE_ERROR = 'REQUEST_DATERANGE_ERROR';
export const REQUEST_DATERANGE_SUCCESS = 'REQUEST_DATERANGE_SUCCESS';


