
export  const REQUEST_USER_INFO_LOADING = 'REQUEST_USER_INFO_LOADING';
export  const REQUEST_USER_INFO_ERROR = 'REQUEST_USER_INFO_ERROR';
export  const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS';

export const RESET_USER_INFO = 'RESET_USER_INFO';
