

export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';



export  const REQUEST_LOADING = 'REQUEST_LOADING';


export  const REQUEST_VALIDPHONE_ERROR = 'REQUEST_VALIDPHONE_ERROR';
export  const REQUEST_VALIDPHONE_SUCCESS = 'REQUEST_VALIDPHONE_SUCCESS';


export  const REQUEST_VALIDCODE_ERROR = 'REQUEST_VALIDCODE_ERROR';
export  const REQUEST_VALIDCODE_SUCCESS = 'REQUEST_VALIDCODE_SUCCESS';
