


export  const REQUEST_ROB_TRAIN_LOADING = 'REQUEST_ROB_TRAIN_LOADING';
export  const REQUEST_ROB_TRAIN_ERROR = 'REQUEST_ROB_TRAIN_ERROR';
export  const REQUEST_ROB_TRAIN_SUCCESS = 'REQUEST_ROB_TRAIN_SUCCESS';


