
export  const REQUEST_CHANGE_ACCOUNT_USER_INFO_LOADING = 'REQUEST_CHANGE_ACCOUNT_USER_INFO_LOADING';
export  const REQUEST_CHANGE_ACCOUNT_USER_INFO_ERROR = 'REQUEST_CHANGE_ACCOUNT_USER_INFO_ERROR';
export  const REQUEST_CHANGE_ACCOUNT_USER_INFO_SUCCESS = 'REQUEST_CHANGE_ACCOUNT_USER_INFO_SUCCESS';

export  const REQUEST_USER_INFO_LOADING = 'REQUEST_USER_INFO_LOADING';
export  const REQUEST_USER_INFO_ERROR = 'REQUEST_USER_INFO_ERROR';
export  const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS';

export const RESET_ERROR = 'RESET_ERROR';