
export	const SEARCH_DATE_CHANGE = 'SEARCH_DATE_CHANGE';
export	const SHOW_DATE_MODAL = 'SHOW_DATE_MODAL';
export	const HIDE_DATE_MODAL= 'HIDE_DATE_MODAL';
export	const FIND_CHANGE = 'FIND_CHANGE';

export 	const REQUEST_LOADING = 'REQUEST_LOADING';
export  const REQUEST_ERROR = 'REQUEST_ERROR';
export  const REQUEST_DATE_RANGE_SUCCESS = 'REQUEST_DATE_RANGE_SUCCESS';

