

export const REQUEST_TRAIN_FILLORDER_LOADIND = 'REQUEST_TRAIN_FILLORDER_LOADIND';
export const REQUEST_TRAIN_FILLORDER_ERROR = 'REQUEST_TRAIN_FILLORDER_ERROR';


export const INIT_TRAIN_INFO = 'INIT_TRAIN_INFO';
export const INIF_TRAIN_PASSENGER = 'INIF_TRAIN_PASSENGER';
export const RESET_TRAIN_FILLORDER_ERROR = 'RESET_TRAIN_FILLORDER_ERROR';



export const REQUEST_TRAIN_FILLORDER_INSURANCE_SUCCESS = "REQUEST_TRAIN_FILLORDER_INSURANCE_SUCCESS";
export const REQUEST_TRAIN_FILLORDER_USER_INFO_SUCCESS = 'REQUEST_TRAIN_FILLORDER_USER_INFO_SUCCESS';
export const REQUEST_TRAIN_FILLORDER_LOGIN12306_SUCCESS ='REQUEST_TRAIN_FILLORDER_LOGIN12306_SUCCESS';
export const REQUEST_TRAIN_FILLORDER_CANCEL_ORDER_SUCCESS = 'REQUEST_TRAIN_FILLORDER_CANCEL_ORDER_SUCCESS';



export const REQUEST_TRAIN_FILLORDER_SUBMIT_LOADIND = 'REQUEST_TRAIN_FILLORDER_SUBMIT_LOADIND';
export const REQUEST_TRAIN_FILLORDER_SUBMIT_SUCCESS = 'REQUEST_TRAIN_FILLORDER_SUBMIT_SUCCESS';
export const REQUEST_TRAIN_FILLORDER_SUBMIT_ERROR  = 'REQUEST_TRAIN_FILLORDER_SUBMIT_ERROR';
