

export const REQUEST_LOADIND = 'REQUEST_LOADIND';

export const INIT_TRAIN_INFO = 'INIT_TRAIN_INFO';


export const REQUEST_INSURANCE_SUCCESS = "REQUEST_INSURANCE_SUCCESS";
export const REQUEST_INSURANCE_ERROR = 'REQUEST_INSURANCE_ERROR';

export  const REQUEST_USER_INFO_ERROR = 'REQUEST_USER_INFO_ERROR';
export  const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS';

