


export const REQUEST_TRAIN_ORDER_LOADIND = 'REQUEST_TRAIN_ORDER_LOADIND';
export const REQUEST_TRAIN_ORDER_ERROR = 'REQUEST_TRAIN_ORDER_ERROR';
export const REQUEST_TRAIN_ORDER_SUCCESS = 'REQUEST_TRAIN_ORDER_SUCCESS';


