
export	const SEARCH_DATE_CHANGE = 'SEARCH_DATE_CHANGE';
export	const SHOW_DATE_MODAL = 'SHOW_DATE_MODAL';
export	const HIDE_DATE_MODAL= 'HIDE_DATE_MODAL';

export 	const REQUEST_BUS_RECOMMEND_LOADING = 'REQUEST_BUS_RECOMMEND_LOADING';
export  const REQUEST_BUS_RECOMMEND_SUCCESS = 'REQUEST_BUS_RECOMMEND_SUCCESS';
export  const REQUEST_BUS_RECOMMEND_ERROR = 'REQUEST_BUS_RECOMMEND_ERROR';

export const REQUEST_INIT_PARAMS = 'REQUEST_INIT_PARAMS';



